<?php

namespace Tests\Feature;

//use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Company;
use App\Models\User;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class ApiCompanyTest extends TestCase
{
    use WithFaker;

    /**
     * @var string|\Laravel\Sanctum\string
     */
    protected string $token;
    protected Company $company;
    protected string $baseUrl = '/api/v1/companies';

    /**
     * Setup the test environment.
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::beginTransaction();
        $email = $this->faker->safeEmail();
        $password = "password";
        /**
         * @var User $user
         */
        $user = User::factory(
            [
                'first_name' => $this->faker->firstName(),
                'last_name' => $this->faker->lastName(),
                'email' => $email,
                'password' => Hash::make($password),
            ]
        )->create();
        $this->token = $user->createToken('ApiToken')->plainTextToken;
        $this->company = Company::factory()->create();
    }

    /**
     * Get all resources.
     *
     * @return void
     */
    public function test_get_all_companies_successful_response()
    {
        $response = $this->get($this->baseUrl, [
            'Authorization' => 'Bearer ' . $this->token,
            'perPage' => 10,
            'page' => 1,
        ]);

        $response->assertStatus(200);
    }

    /**
     * Get specified resource by id
     *
     * @return void
     */
    public function test_get_company_by_id_successful_response()
    {
        $response = $this->get($this->baseUrl  . DIRECTORY_SEPARATOR . $this->company->id,
            [
                'Authorization' => 'Bearer ' . $this->token,
            ]);

        $response->assertStatus(200);
    }

    /**
     * Get specified resource by id
     *
     * @return void
     */
    public function test_get_company_by_id_not_found_exception_response()
    {
        $response = $this->get($this->baseUrl . DIRECTORY_SEPARATOR . $this->faker->uuid,
            [
                'Authorization' => 'Bearer ' . $this->token,
            ]);

        $response->assertStatus(404);
    }

    /**
     * Create resource
     *
     * @return void
     */
    public function test_create_company_validation_exception_response()
    {
        $response = $this->post($this->baseUrl,
            [
                'name' => $this->faker->name,
                'location' => $this->faker->address,
            ],
            [
                'Authorization' => 'Bearer ' . $this->token,
            ]
        );

        $response->assertStatus(422);
    }

    /**
     * @return void
     */
    protected function tearDown(): void
    {
        DB::rollBack();
    }

}
